---
- name: Create users and groups
  hosts: all
  become: yes
  tasks:
    - name: Create devops group
      group:
        name: devops
        state: present

    - name: Create qa group
      group:
        name: qa
        state: present

    - name: Create user mokhira
      user:
        name: mokhira
        groups: devops
        state: present
        shell: /bin/bash

    - name: Create user tim
      user:
        name: tim
        groups: qa
        state: present
       

    - name: Create user ann
      user:
        name: ann
        groups: qa
        state: present
        
